import { useState } from "react";
import JSZip from "jszip";
import type {
  Blueprint,
  ProductionCodebase,
  PrototypeData,
  PrototypeFile,
  PrototypeScreen,
  StudentProfile,
} from "@/lib/types";
import { generateProductionBatch, generateProductionManifest } from "@/lib/quest.functions";

export function PrototypeSandbox({
  prototype,
  blueprint,
  profile,
  onBackToBlueprint,
}: {
  prototype: PrototypeData;
  blueprint: Blueprint;
  profile: StudentProfile | null;
  onBackToBlueprint: () => void;
}) {
  const screens = prototype?.screens || [];
  const codeFiles = prototype?.codeFiles || [];
  const runInstructions = prototype?.runInstructions || [];

  const [activeTab, setActiveTab] = useState<"preview" | "code" | "guide" | "production">("preview");
  const [activeScreenId, setActiveScreenId] = useState<string>(
    screens[0]?.id || "dashboard"
  );
  const [selectedFileIndex, setSelectedFileIndex] = useState<number>(0);
  const [copiedFile, setCopiedFile] = useState(false);
  const [isZipping, setIsZipping] = useState(false);

  // Production Engine State (Manifest + Batch Loop)
  const [productionCodebase, setProductionCodebase] = useState<ProductionCodebase | null>(
    prototype?.productionCodebase || null
  );
  const [isBuildingProduction, setIsBuildingProduction] = useState(false);
  const [productionStepMsg, setProductionStepMsg] = useState<string>("");
  const [selectedProdFileIndex, setSelectedProdFileIndex] = useState<number>(0);
  const [isProdZipping, setIsProdZipping] = useState(false);
  const [copiedProdFile, setCopiedProdFile] = useState(false);
  const [prodViewMode, setProdViewMode] = useState<"files" | "contract">("files");

  // Interactive mock form state
  const [formValues, setFormValues] = useState<Record<string, string>>({});
  const [formFeedback, setFormFeedback] = useState<string | null>(null);
  const [simulatedLogs, setSimulatedLogs] = useState<string[]>([]);

  const activeScreen: PrototypeScreen | undefined =
    screens.find((s) => s.id === activeScreenId) || screens[0];

  const selectedFile = codeFiles[selectedFileIndex] || codeFiles[0];

  const handleDownloadZip = async () => {
    try {
      setIsZipping(true);
      const zip = new JSZip();

      // Add all AI generated code files
      for (const file of codeFiles) {
        zip.file(file.path, file.code);
      }

      // Add run instructions as RUN_GUIDE.md
      const instructionsList = runInstructions
        .map((inst, i) => `${i + 1}. \`${inst}\``)
        .join("\n");
      const runGuide = `# Quick Start Guide for ${prototype?.title || "Sarthi Prototype"}\n\n## Architecture Overview\n${prototype?.architectureSummary || "Interactive Prototype"}\n\n## Setup Instructions\n${instructionsList}\n\nGenerated by Sarthi AI Project Charioteer.`;
      zip.file("RUN_GUIDE.md", runGuide);

      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      const sanitizedName = (prototype?.title || "sarthi-prototype")
        .toLowerCase()
        .replace(/[^a-z0-9]/g, "-")
        .replace(/-+/g, "-");
      a.download = `${sanitizedName}-starter.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Failed to create ZIP package:", err);
    } finally {
      setIsZipping(false);
    }
  };

  const handleCopyCode = async () => {
    if (!selectedFile) return;
    try {
      await navigator.clipboard.writeText(selectedFile.code);
      setCopiedFile(true);
      setTimeout(() => setCopiedFile(false), 2000);
    } catch {
      /* ignore */
    }
  };

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (activeScreen?.inputForm) {
      setFormFeedback(activeScreen.inputForm.successMessage);
      const logEntry = `[${new Date().toLocaleTimeString()}] Form submitted: ${JSON.stringify(formValues)}`;
      setSimulatedLogs((prev) => [logEntry, ...prev.slice(0, 5)]);
    }
  };

  const handleActionClick = (mockResponse: string, label: string) => {
    const logEntry = `[${new Date().toLocaleTimeString()}] Triggered "${label}": ${mockResponse}`;
    setSimulatedLogs((prev) => [logEntry, ...prev.slice(0, 5)]);
  };

  const handleStartProductionBuild = async () => {
    if (!profile) return;
    try {
      setIsBuildingProduction(true);
      setProductionStepMsg("Phase 1: Establishing Shared Architectural Contract & Batch Schedule...");

      // Step 1: Manifest Generation
      const manifest = await generateProductionManifest({
        data: { profile, blueprint },
      });

      let currentFiles: PrototypeFile[] = [];
      const completedBatchIds: string[] = [];

      setProductionCodebase({
        manifest,
        files: currentFiles,
        completedBatchIds,
        isGenerating: true,
        currentBatchIndex: 0,
      });

      // Step 2: Batch Loop
      for (let i = 0; i < manifest.batches.length; i++) {
        const batch = manifest.batches[i];
        setProductionStepMsg(
          `Phase 2: Compiling ${batch.layerName} (${batch.targetFiles.length} files)...`
        );

        const batchFiles = await generateProductionBatch({
          data: {
            batch,
            manifestContract: {
              databaseContract: manifest.databaseContract,
              apiContract: manifest.apiContract,
              envContract: manifest.envContract,
            },
            blueprint,
            profile,
          },
        });

        currentFiles = [...currentFiles, ...batchFiles];
        completedBatchIds.push(batch.id);

        setProductionCodebase({
          manifest,
          files: currentFiles,
          completedBatchIds,
          isGenerating: i < manifest.batches.length - 1,
          currentBatchIndex: i + 1,
        });
      }

      setProductionStepMsg("✓ Full production-grade application successfully generated!");
    } catch (err) {
      console.error("Production build failed:", err);
      setProductionStepMsg(
        `Error during generation: ${err instanceof Error ? err.message : String(err)}`
      );
    } finally {
      setIsBuildingProduction(false);
    }
  };

  const handleDownloadProductionZip = async () => {
    if (!productionCodebase) return;
    try {
      setIsProdZipping(true);
      const zip = new JSZip();

      for (const file of productionCodebase.files) {
        zip.file(file.path, file.code);
      }

      if (!productionCodebase.files.some((f) => f.path === "database/schema.sql")) {
        zip.file("database/schema.sql", productionCodebase.manifest.databaseContract);
      }
      if (!productionCodebase.files.some((f) => f.path === ".env.example")) {
        zip.file(".env.example", productionCodebase.manifest.envContract.join("\n"));
      }

      const archMarkdown = `# ${productionCodebase.manifest.title} - Production Architecture Guide

## Architecture Summary
${productionCodebase.manifest.description}

## REST API Endpoints Contract
| Method | Path | Summary |
|---|---|---|
${productionCodebase.manifest.apiContract
  .map((ep) => `| \`${ep.method}\` | \`${ep.path}\` | ${ep.summary} |`)
  .join("\n")}

## Environment Variables
\`\`\`bash
${productionCodebase.manifest.envContract.join("\n")}
\`\`\`

## Database Schema (PostgreSQL DDL)
\`\`\`sql
${productionCodebase.manifest.databaseContract}
\`\`\`

Generated via Sarthi Manifest + Batch Loop Engine.
`;
      zip.file("ARCHITECTURE.md", archMarkdown);

      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      const sanitizedName = (productionCodebase.manifest.title || "production-app")
        .toLowerCase()
        .replace(/[^a-z0-9]/g, "-")
        .replace(/-+/g, "-");
      a.download = `${sanitizedName}-production-fullstack.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Failed to download production zip:", err);
    } finally {
      setIsProdZipping(false);
    }
  };

  const handleCopyProdCode = async (code: string) => {
    try {
      await navigator.clipboard.writeText(code);
      setCopiedProdFile(true);
      setTimeout(() => setCopiedProdFile(false), 2000);
    } catch {
      /* ignore */
    }
  };

  return (
    <div className="space-y-6">
      {/* Top Header Card */}
      <div className="panel q-rise overflow-hidden border-2 border-border">
        <div className="flex flex-wrap items-center justify-between gap-4 border-b-2 border-border bg-gradient-to-r from-accent/20 via-background to-accent/10 px-6 py-5">
          <div>
            <div className="flex flex-wrap items-center gap-2">
              <span className="mono-label rounded-full bg-accent px-2.5 py-0.5 font-bold text-accent-foreground">
                STAGE 6: PROTOTYPE FORGE
              </span>
              <span className="mono-label text-muted-foreground">
                interactive software preview & codebase
              </span>
            </div>
            <h2 className="font-display mt-1 text-3xl font-extrabold">{prototype.title}</h2>
            <p className="mt-1 text-sm text-muted-foreground italic">{prototype.tagline}</p>
          </div>

          <div className="flex flex-wrap items-center gap-3">
            <button
              onClick={onBackToBlueprint}
              className="btn-brutal bg-background text-xs sm:text-sm px-3.5 py-2"
            >
              ← Back to Blueprint
            </button>
            <button
              onClick={handleDownloadZip}
              disabled={isZipping}
              className="btn-brutal flex items-center gap-2 bg-accent px-4 py-2 text-xs sm:text-sm font-bold text-accent-foreground shadow-md"
            >
              <span>📦</span>
              <span>{isZipping ? "Packaging ZIP..." : "Download Starter ZIP"}</span>
            </button>
          </div>
        </div>

        {/* Navigation Tabs */}
        <div className="flex flex-wrap border-b-2 border-border bg-sunken px-6">
          <button
            onClick={() => setActiveTab("preview")}
            className={`flex items-center gap-2 border-b-2 px-4 py-3 text-sm font-extrabold transition-colors ${
              activeTab === "preview"
                ? "border-accent text-accent"
                : "border-transparent text-muted-foreground hover:text-foreground"
            }`}
          >
            <span>🖥️</span>
            <span>Interactive Live Sandbox</span>
            <span className="rounded-full bg-accent/20 px-2 py-0.5 text-xs text-accent">Live</span>
          </button>
          <button
            onClick={() => setActiveTab("code")}
            className={`flex items-center gap-2 border-b-2 px-4 py-3 text-sm font-extrabold transition-colors ${
              activeTab === "code"
                ? "border-accent text-accent"
                : "border-transparent text-muted-foreground hover:text-foreground"
            }`}
          >
            <span>💻</span>
            <span>Codebase Explorer</span>
            <span className="rounded-full bg-sunken px-2 py-0.5 text-xs font-mono">
              {codeFiles.length} files
            </span>
          </button>
          <button
            onClick={() => setActiveTab("production")}
            className={`flex items-center gap-2 border-b-2 px-4 py-3 text-sm font-extrabold transition-colors ${
              activeTab === "production"
                ? "border-accent text-accent"
                : "border-transparent text-muted-foreground hover:text-foreground"
            }`}
          >
            <span>⚡</span>
            <span>Production Hub (Manifest Engine)</span>
            <span className="rounded-full bg-emerald-500/20 px-2 py-0.5 text-xs text-emerald-400 font-mono font-bold">
              {productionCodebase && productionCodebase.files.length > 0
                ? `${productionCodebase.files.length} Files`
                : "Batch Loop"}
            </span>
          </button>
          <button
            onClick={() => setActiveTab("guide")}
            className={`flex items-center gap-2 border-b-2 px-4 py-3 text-sm font-extrabold transition-colors ${
              activeTab === "guide"
                ? "border-accent text-accent"
                : "border-transparent text-muted-foreground hover:text-foreground"
            }`}
          >
            <span>🚀</span>
            <span>Local Setup & Guide</span>
          </button>
        </div>
      </div>

      {/* Architecture Context Banner */}
      <div className="panel border-2 border-border bg-sunken px-5 py-3.5 text-xs sm:text-sm text-muted-foreground flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2 min-w-0">
          <span className="text-base">🧭</span>
          <span className="font-bold text-foreground">Sarthi's Architecture Translation:</span>
          <span className="truncate">{prototype?.architectureSummary || "Interactive Prototype Sandbox"}</span>
        </div>
        <div className="flex flex-wrap items-center gap-1.5">
          {((blueprint?.stack || (blueprint as any)?.techStack || []) as any[]).slice(0, 4).map((tech: any) => {
            const name = typeof tech === "string" ? tech : tech?.name;
            if (!name) return null;
            return (
              <span
                key={name}
                className="mono-label rounded-md bg-background border border-border px-2 py-0.5 text-[11px] font-semibold text-foreground"
              >
                {name}
              </span>
            );
          })}
        </div>
      </div>

      {/* TAB 1: INTERACTIVE LIVE PREVIEW */}
      {activeTab === "preview" && (
        <div className="space-y-4">
          {/* Mock Browser Container */}
          <div className="panel overflow-hidden border-2 border-border shadow-2xl">
            {/* Browser Window Header */}
            <div className="flex flex-wrap items-center justify-between gap-3 border-b-2 border-border bg-sunken px-4 py-2.5">
              <div className="flex items-center gap-2">
                <div className="flex gap-1.5">
                  <div className="size-3 rounded-full bg-destructive/70" />
                  <div className="size-3 rounded-full bg-amber-500/70" />
                  <div className="size-3 rounded-full bg-emerald-500/70" />
                </div>
                <div className="ml-3 flex items-center gap-2 rounded-md border border-border bg-background px-3 py-1 font-mono text-xs text-muted-foreground">
                  <span className="text-emerald-500">🔒</span>
                  <span>https://sarthi-local-app.test/{activeScreen?.id}</span>
                </div>
              </div>

              {/* In-App Screen Navigation Tabs */}
              <div className="flex items-center gap-1.5 overflow-x-auto">
                {screens.map((screen) => (
                  <button
                    key={screen.id}
                    onClick={() => {
                      setActiveScreenId(screen.id);
                      setFormFeedback(null);
                    }}
                    className={`rounded-lg px-3 py-1 text-xs font-bold transition-all ${
                      activeScreenId === screen.id
                        ? "bg-foreground text-background shadow"
                        : "bg-background text-muted-foreground hover:bg-sunken hover:text-foreground"
                    }`}
                  >
                    {screen.title}
                  </button>
                ))}
              </div>
            </div>

            {/* Simulated Live View Body */}
            {activeScreen && (
              <div className="bg-background p-6 space-y-6 min-h-[480px]">
                {/* Screen Header */}
                <div className="border-b border-border pb-4">
                  <span className="mono-label text-accent font-bold">VIEW: {activeScreen.id.toUpperCase()}</span>
                  <h3 className="font-display text-2xl font-extrabold">{activeScreen.title}</h3>
                  <p className="mt-1 text-sm text-muted-foreground">{activeScreen.subtitle}</p>
                </div>

                {/* Metrics Row (if present) */}
                {activeScreen.metrics && activeScreen.metrics.length > 0 && (
                  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                    {activeScreen.metrics.map((m) => (
                      <div
                        key={m.label}
                        className="rounded-xl border-2 border-border bg-sunken p-4 space-y-1 shadow-sm"
                      >
                        <p className="mono-label text-muted-foreground text-xs">{m.label}</p>
                        <div className="flex items-baseline justify-between">
                          <p className="font-display text-2xl font-extrabold">{m.value}</p>
                          {m.change && (
                            <span className="rounded-full bg-emerald-500/15 px-2 py-0.5 text-xs font-bold text-emerald-600">
                              {m.change}
                            </span>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                )}

                <div className="grid gap-6 lg:grid-cols-2">
                  {/* Left Column: Interactive Input Form or Action Center */}
                  {activeScreen.inputForm ? (
                    <div className="rounded-xl border-2 border-border bg-card p-5 space-y-4">
                      <div>
                        <h4 className="font-display text-lg font-bold">
                          {activeScreen.inputForm.title}
                        </h4>
                        <p className="text-xs text-muted-foreground">
                          {activeScreen.inputForm.description}
                        </p>
                      </div>

                      <form onSubmit={handleFormSubmit} className="space-y-3">
                        {activeScreen.inputForm.fields.map((field) => (
                          <div key={field.name} className="space-y-1">
                            <label className="mono-label text-xs font-semibold block">
                              {field.label}
                            </label>
                            {field.type === "select" ? (
                              <select
                                value={formValues[field.name] || ""}
                                onChange={(e) =>
                                  setFormValues({ ...formValues, [field.name]: e.target.value })
                                }
                                className="w-full rounded-lg border-2 border-border bg-background px-3 py-2 text-sm focus:border-accent focus:outline-none"
                              >
                                <option value="">Select an option...</option>
                                {field.options?.map((opt) => (
                                  <option key={opt} value={opt}>
                                    {opt}
                                  </option>
                                ))}
                              </select>
                            ) : field.type === "textarea" ? (
                              <textarea
                                rows={2}
                                value={formValues[field.name] || ""}
                                onChange={(e) =>
                                  setFormValues({ ...formValues, [field.name]: e.target.value })
                                }
                                placeholder={field.placeholder}
                                className="w-full rounded-lg border-2 border-border bg-background px-3 py-2 text-sm focus:border-accent focus:outline-none"
                              />
                            ) : (
                              <input
                                type={field.type}
                                value={formValues[field.name] || ""}
                                onChange={(e) =>
                                  setFormValues({ ...formValues, [field.name]: e.target.value })
                                }
                                placeholder={field.placeholder}
                                className="w-full rounded-lg border-2 border-border bg-background px-3 py-2 text-sm focus:border-accent focus:outline-none"
                              />
                            )}
                          </div>
                        ))}

                        <button
                          type="submit"
                          className="btn-brutal w-full bg-accent py-2 text-sm font-bold text-accent-foreground"
                        >
                          {activeScreen.inputForm.submitLabel}
                        </button>
                      </form>

                      {formFeedback && (
                        <div className="rounded-lg border-2 border-emerald-500 bg-emerald-500/10 p-3 text-xs text-emerald-800 dark:text-emerald-200 animate-fadeIn">
                          <p className="font-bold flex items-center gap-1.5">
                            <span>✓</span> Simulated Response Received
                          </p>
                          <p className="mt-1">{formFeedback}</p>
                        </div>
                      )}
                    </div>
                  ) : (
                    <div className="rounded-xl border-2 border-border bg-card p-5 space-y-4">
                      <h4 className="font-display text-lg font-bold">Interactive Test Triggers</h4>
                      <p className="text-xs text-muted-foreground">
                        Simulate asynchronous events, queue processors, and background API tasks.
                      </p>
                      {activeScreen.actions && activeScreen.actions.length > 0 ? (
                        <div className="space-y-2">
                          {activeScreen.actions.map((act) => (
                            <div
                              key={act.id}
                              className="flex items-center justify-between rounded-lg border border-border bg-sunken p-3"
                            >
                              <div>
                                <p className="text-sm font-bold">{act.label}</p>
                                <p className="text-xs text-muted-foreground">{act.description}</p>
                              </div>
                              <button
                                onClick={() => handleActionClick(act.mockResponse, act.label)}
                                className="btn-brutal bg-background text-xs px-3 py-1.5"
                              >
                                Trigger
                              </button>
                            </div>
                          ))}
                        </div>
                      ) : (
                        <p className="text-xs text-muted-foreground italic">
                          No custom actions defined for this view.
                        </p>
                      )}
                    </div>
                  )}

                  {/* Right Column: Sample Data Feed & Logs */}
                  <div className="space-y-4">
                    {activeScreen.sampleItems && activeScreen.sampleItems.length > 0 && (
                      <div className="rounded-xl border-2 border-border bg-card p-5 space-y-3">
                        <h4 className="font-display text-lg font-bold">Live Mock Data Stream</h4>
                        <div className="space-y-2">
                          {activeScreen.sampleItems.map((item, idx) => (
                            <div
                              key={item.title + idx}
                              className="flex items-start justify-between rounded-lg border border-border bg-sunken p-3 text-xs"
                            >
                              <div className="space-y-0.5">
                                <p className="font-bold text-foreground text-sm">{item.title}</p>
                                <p className="text-muted-foreground">{item.detail}</p>
                              </div>
                              <div className="text-right">
                                <span className="rounded-full bg-accent/20 px-2 py-0.5 text-[10px] font-bold text-accent">
                                  {item.category}
                                </span>
                                <p className="mono-label text-[10px] text-muted-foreground mt-1">
                                  {item.status}
                                </p>
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Quick Action Trigger Buttons if InputForm exists */}
                    {activeScreen.inputForm && activeScreen.actions && activeScreen.actions.length > 0 && (
                      <div className="rounded-xl border border-border bg-sunken p-4 space-y-2">
                        <p className="mono-label text-xs font-bold">Quick Simulation Triggers</p>
                        <div className="flex flex-wrap gap-2">
                          {activeScreen.actions.map((act) => (
                            <button
                              key={act.id}
                              onClick={() => handleActionClick(act.mockResponse, act.label)}
                              className="rounded-md border border-border bg-background px-3 py-1 text-xs font-medium hover:border-accent"
                            >
                              ⚡ {act.label}
                            </button>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </div>

                {/* Simulated API Console Logs */}
                {simulatedLogs.length > 0 && (
                  <div className="rounded-xl border-2 border-border bg-sunken p-4 space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="mono-label text-xs text-muted-foreground flex items-center gap-1.5">
                        <span className="size-2 rounded-full bg-emerald-500 animate-pulse" />
                        SIMULATED WEBSOCKET & API ACTIVITY LOG
                      </span>
                      <button
                        onClick={() => setSimulatedLogs([])}
                        className="text-[11px] text-muted-foreground hover:text-foreground"
                      >
                        Clear logs
                      </button>
                    </div>
                    <div className="font-mono text-xs space-y-1 text-foreground/90 max-h-32 overflow-y-auto">
                      {simulatedLogs.map((log, i) => (
                        <p key={i} className="leading-relaxed">
                          <span className="text-accent">▸</span> {log}
                        </p>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      )}

      {/* TAB 2: CODEBASE EXPLORER */}
      {activeTab === "code" && (
        <div className="panel overflow-hidden border-2 border-border shadow-2xl">
          <div className="grid lg:grid-cols-4 min-h-[580px]">
            {/* Left File Tree Sidebar */}
            <div className="border-b-2 lg:border-b-0 lg:border-r-2 border-border bg-sunken p-4 space-y-3">
              <div className="flex items-center justify-between pb-2 border-b border-border">
                <span className="mono-label font-bold text-xs">PROJECT REPO FILES</span>
                <span className="mono-label text-[11px] text-muted-foreground">
                  {codeFiles.length} files
                </span>
              </div>
              <div className="space-y-1.5">
                {codeFiles.map((f, i) => (
                  <button
                    key={f.path}
                    onClick={() => {
                      setSelectedFileIndex(i);
                      setCopiedFile(false);
                    }}
                    className={`w-full flex items-center gap-2 rounded-lg px-3 py-2 text-left font-mono text-xs transition-colors ${
                      selectedFileIndex === i
                        ? "bg-foreground text-background font-bold shadow"
                        : "hover:bg-background text-foreground/80"
                    }`}
                  >
                    <span>{f.language === "python" ? "🐍" : f.language === "typescript" ? "⚛️" : f.language === "sql" ? "🗄️" : "📄"}</span>
                    <span className="truncate">{f.path}</span>
                  </button>
                ))}
              </div>

              <div className="pt-4 mt-6 border-t border-border">
                <button
                  onClick={handleDownloadZip}
                  disabled={isZipping}
                  className="btn-brutal w-full flex items-center justify-center gap-2 bg-accent py-2 text-xs font-bold text-accent-foreground"
                >
                  <span>📦</span>
                  <span>{isZipping ? "Zipping..." : "Download Complete Repo ZIP"}</span>
                </button>
              </div>
            </div>

            {/* Right Code Display */}
            <div className="lg:col-span-3 flex flex-col bg-background">
              {selectedFile && (
                <>
                  {/* File Header */}
                  <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border bg-sunken px-5 py-3">
                    <div>
                      <div className="flex items-center gap-2 font-mono text-sm font-bold">
                        <span>{selectedFile.path}</span>
                        <span className="mono-label text-[10px] rounded bg-background border px-1.5 py-0.5">
                          {selectedFile.language.toUpperCase()}
                        </span>
                      </div>
                      <p className="text-xs text-muted-foreground mt-0.5">
                        {selectedFile.description}
                      </p>
                    </div>

                    <button
                      onClick={handleCopyCode}
                      className="btn-brutal bg-background text-xs px-3 py-1.5 font-bold"
                    >
                      {copiedFile ? "✓ Copied to Clipboard!" : "📋 Copy Code"}
                    </button>
                  </div>

                  {/* Code Block */}
                  <div className="flex-1 p-4 font-mono text-xs bg-zinc-950 text-zinc-100 overflow-x-auto leading-relaxed max-h-[600px]">
                    <pre className="whitespace-pre">
                      <code>{selectedFile.code}</code>
                    </pre>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      )}

      {/* TAB 3: LOCAL SETUP & GUIDE */}
      {activeTab === "guide" && (
        <div className="space-y-6">
          <div className="panel border-2 border-border p-6 space-y-4">
            <div className="border-b border-border pb-3">
              <span className="mono-label text-accent font-bold">SARTHI RUNBOOK</span>
              <h3 className="font-display text-2xl font-extrabold">How to Run this Prototype Locally</h3>
              <p className="text-sm text-muted-foreground">
                Follow these terminal commands to boot your full-stack prototype on your local machine.
              </p>
            </div>

            <ol className="space-y-4">
              {runInstructions.map((instruction, index) => (
                <li
                  key={index}
                  className="flex items-start gap-3 rounded-xl border-2 border-border bg-sunken p-4"
                >
                  <span className="grid size-7 shrink-0 place-items-center rounded-full bg-accent font-display text-sm font-extrabold text-accent-foreground">
                    {index + 1}
                  </span>
                  <div className="flex-1 space-y-1">
                    <p className="text-sm font-bold text-foreground">Step {index + 1}</p>
                    <p className="font-mono text-xs bg-background p-2 rounded border border-border text-accent">
                      {instruction}
                    </p>
                  </div>
                </li>
              ))}
            </ol>
          </div>

          {/* Sarthi Guidance for College Guides */}
          <div className="panel border-2 border-border bg-gradient-to-r from-accent/10 via-background to-accent/5 p-6 space-y-3">
            <div className="flex items-center gap-2">
              <span className="text-2xl">🏹</span>
              <h4 className="font-display text-lg font-bold">
                How to Present this Prototype to Your College Guide
              </h4>
            </div>
            <ul className="space-y-2 text-xs sm:text-sm text-muted-foreground leading-relaxed">
              <li className="flex gap-2">
                <span className="text-accent font-bold">1.</span>
                <span>
                  <strong>Demonstrate User Flow First:</strong> Open the <em>Interactive Live Sandbox</em> tab during your project review. Walk your guide through the mock screens to show the exact student/user experience before diving into technical details.
                </span>
              </li>
              <li className="flex gap-2">
                <span className="text-accent font-bold">2.</span>
                <span>
                  <strong>Show Architectural Grounding:</strong> Switch to the <em>Codebase Explorer</em> tab to prove that the database schemas, API routes, and components are already planned and scaffolded.
                </span>
              </li>
              <li className="flex gap-2">
                <span className="text-accent font-bold">3.</span>
                <span>
                  <strong>Download Starter ZIP:</strong> Unzip the repo on your machine to begin implementing Phase 1 from your Blueprint roadmap!
                </span>
              </li>
            </ul>
          </div>
        </div>
      )}

      {/* TAB 4: PRODUCTION HUB (MANIFEST + BATCH LOOP) */}
      {activeTab === "production" && (
        <div className="space-y-6">
          {/* Top Control Panel */}
          <div className="panel border-2 border-border p-6 space-y-5 bg-gradient-to-r from-emerald-950/20 via-background to-teal-950/10">
            <div className="flex flex-wrap items-center justify-between gap-4 border-b border-border pb-4">
              <div>
                <div className="flex items-center gap-2">
                  <span className="mono-label rounded-full bg-emerald-500/20 px-2.5 py-0.5 text-xs font-bold text-emerald-400">
                    ENTERPRISE ARCHITECTURE
                  </span>
                  <span className="mono-label text-muted-foreground text-xs">
                    Manifest + Batch Loop Engine
                  </span>
                </div>
                <h3 className="font-display text-2xl sm:text-3xl font-extrabold mt-1">
                  Production-Grade Full-Stack Repository
                </h3>
                <p className="text-sm text-muted-foreground max-w-2xl mt-1">
                  Compiles a fully interconnected 10-15 file production repository. The AI establishes an immutable database & API contract first, then topologically generates each layer to guarantee zero code conflicts or token cuts.
                </p>
              </div>

              <div className="flex flex-wrap items-center gap-3">
                <button
                  onClick={handleStartProductionBuild}
                  disabled={isBuildingProduction}
                  className="btn-brutal flex items-center gap-2 bg-emerald-500 px-4 py-2.5 text-xs sm:text-sm font-bold text-emerald-950 shadow-md hover:bg-emerald-400 disabled:opacity-50"
                >
                  <span>{isBuildingProduction ? "⚙️" : "⚡"}</span>
                  <span>
                    {isBuildingProduction
                      ? "Assembling Layers..."
                      : productionCodebase
                      ? "Re-assemble Production App"
                      : "Manifest & Build Production App"}
                  </span>
                </button>

                {productionCodebase && productionCodebase.files.length > 0 && (
                  <button
                    onClick={handleDownloadProductionZip}
                    disabled={isProdZipping}
                    className="btn-brutal flex items-center gap-2 bg-accent px-4 py-2.5 text-xs sm:text-sm font-bold text-accent-foreground shadow-md disabled:opacity-50"
                  >
                    <span>📦</span>
                    <span>{isProdZipping ? "Packaging ZIP..." : "Download Full Production ZIP"}</span>
                  </button>
                )}
              </div>
            </div>

            {/* Live Progress Bar and Step Tracker */}
            {(isBuildingProduction || productionStepMsg) && (
              <div className="rounded-xl border-2 border-border bg-sunken p-4 space-y-2">
                <div className="flex items-center justify-between text-xs font-mono">
                  <span className="text-foreground font-bold flex items-center gap-2">
                    {isBuildingProduction && <span className="animate-spin inline-block">⏳</span>}
                    {productionStepMsg}
                  </span>
                  {productionCodebase && (
                    <span className="text-accent font-bold">
                      {productionCodebase.completedBatchIds.length} / {productionCodebase.manifest.batches.length} Layers
                    </span>
                  )}
                </div>
                <div className="h-2 w-full overflow-hidden rounded-full bg-border">
                  <div
                    className="h-full bg-emerald-500 transition-all duration-500 ease-out"
                    style={{
                      width: productionCodebase
                        ? `${Math.round((productionCodebase.completedBatchIds.length / productionCodebase.manifest.batches.length) * 100)}%`
                        : isBuildingProduction
                        ? "15%"
                        : "100%",
                    }}
                  />
                </div>
              </div>
            )}
          </div>

          {/* If No Codebase Generated Yet: Architectural Walkthrough */}
          {!productionCodebase && !isBuildingProduction && (
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              <div className="panel border-2 border-border p-5 space-y-2 bg-sunken">
                <div className="flex items-center gap-2 font-display font-bold text-base text-foreground">
                  <span className="grid size-6 place-items-center rounded bg-accent text-accent-foreground text-xs font-mono">
                    1
                  </span>
                  <span>Manifest Contract Engine</span>
                </div>
                <p className="text-xs text-muted-foreground leading-relaxed">
                  Establishes the single source of truth: PostgreSQL DDL schemas, REST API endpoints, and environment variables.
                </p>
              </div>

              <div className="panel border-2 border-border p-5 space-y-2 bg-sunken">
                <div className="flex items-center gap-2 font-display font-bold text-base text-foreground">
                  <span className="grid size-6 place-items-center rounded bg-accent text-accent-foreground text-xs font-mono">
                    2
                  </span>
                  <span>Topological Batch Compiler</span>
                </div>
                <p className="text-xs text-muted-foreground leading-relaxed">
                  Generates layers in dependency order (Database → FastAPI Backend → React Client → Docker Orchestration).
                </p>
              </div>

              <div className="panel border-2 border-border p-5 space-y-2 bg-sunken">
                <div className="flex items-center gap-2 font-display font-bold text-base text-foreground">
                  <span className="grid size-6 place-items-center rounded bg-accent text-accent-foreground text-xs font-mono">
                    3
                  </span>
                  <span>Production Ready Export</span>
                </div>
                <p className="text-xs text-muted-foreground leading-relaxed">
                  Downloads a comprehensive multi-folder codebase with docker-compose, ready for local execution and deployment.
                </p>
              </div>
            </div>
          )}

          {/* When Codebase Exists: Explorer and Contract Viewer */}
          {productionCodebase && (
            <div className="space-y-4">
              {/* View Switcher Toggle */}
              <div className="flex items-center justify-between gap-3 border-b border-border pb-2">
                <div className="flex gap-2">
                  <button
                    onClick={() => setProdViewMode("files")}
                    className={`btn-brutal text-xs px-3.5 py-1.5 font-bold ${
                      prodViewMode === "files"
                        ? "bg-accent text-accent-foreground"
                        : "bg-background text-muted-foreground"
                    }`}
                  >
                    📁 Production Files ({productionCodebase.files.length})
                  </button>
                  <button
                    onClick={() => setProdViewMode("contract")}
                    className={`btn-brutal text-xs px-3.5 py-1.5 font-bold ${
                      prodViewMode === "contract"
                        ? "bg-accent text-accent-foreground"
                        : "bg-background text-muted-foreground"
                    }`}
                  >
                    📜 Shared Contracts (DB & APIs)
                  </button>
                </div>

                <div className="text-xs text-muted-foreground font-mono">
                  {productionCodebase.completedBatchIds.length} Layers Compiled
                </div>
              </div>

              {/* FILES VIEW */}
              {prodViewMode === "files" && (
                <div className="panel border-2 border-border overflow-hidden grid lg:grid-cols-[280px_1fr] min-h-[500px]">
                  {/* File List */}
                  <div className="border-r-2 border-border bg-sunken p-3 space-y-1 overflow-y-auto max-h-[650px]">
                    <div className="px-2 py-1 text-[11px] font-mono font-bold text-muted-foreground uppercase tracking-wider">
                      Repository Tree
                    </div>
                    {productionCodebase.files.map((file, idx) => {
                      const isSelected = idx === selectedProdFileIndex;
                      return (
                        <button
                          key={idx}
                          onClick={() => setSelectedProdFileIndex(idx)}
                          className={`w-full text-left px-3 py-2 rounded-lg text-xs font-mono transition-colors flex items-center justify-between gap-2 ${
                            isSelected
                              ? "bg-accent text-accent-foreground font-bold shadow-sm"
                              : "hover:bg-background/80 text-foreground"
                          }`}
                        >
                          <span className="truncate">{file.path}</span>
                          <span className="mono-label text-[10px] opacity-75 shrink-0">
                            {file.language}
                          </span>
                        </button>
                      );
                    })}
                  </div>

                  {/* Code Editor Preview */}
                  <div className="flex flex-col bg-zinc-950">
                    {productionCodebase.files[selectedProdFileIndex] ? (
                      <>
                        <div className="flex items-center justify-between gap-3 border-b border-zinc-800 bg-zinc-900 px-5 py-3 text-zinc-100">
                          <div>
                            <span className="font-mono text-xs font-bold text-emerald-400">
                              {productionCodebase.files[selectedProdFileIndex].path}
                            </span>
                            <p className="text-[11px] text-zinc-400 mt-0.5">
                              {productionCodebase.files[selectedProdFileIndex].description}
                            </p>
                          </div>
                          <button
                            onClick={() =>
                              handleCopyProdCode(
                                productionCodebase.files[selectedProdFileIndex].code
                              )
                            }
                            className="btn-brutal bg-zinc-800 hover:bg-zinc-700 text-xs px-3 py-1.5 text-zinc-200 border-zinc-700"
                          >
                            {copiedProdFile ? "✓ Copied" : "📋 Copy"}
                          </button>
                        </div>
                        <div className="flex-1 p-4 font-mono text-xs text-zinc-100 overflow-x-auto leading-relaxed max-h-[600px]">
                          <pre className="whitespace-pre">
                            <code>{productionCodebase.files[selectedProdFileIndex].code}</code>
                          </pre>
                        </div>
                      </>
                    ) : (
                      <div className="p-8 text-center text-sm text-zinc-500 font-mono">
                        Select a file from the repository tree to inspect.
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* CONTRACT VIEW */}
              {prodViewMode === "contract" && (
                <div className="space-y-6">
                  {/* API Endpoints Contract */}
                  <div className="panel border-2 border-border p-5 space-y-3">
                    <h4 className="font-display text-lg font-bold flex items-center gap-2">
                      <span>🔗</span>
                      <span>REST API Contract ({productionCodebase.manifest.apiContract.length} Endpoints)</span>
                    </h4>
                    <div className="overflow-x-auto">
                      <table className="w-full text-xs text-left border border-border">
                        <thead className="bg-sunken text-muted-foreground uppercase font-mono text-[10px]">
                          <tr>
                            <th className="px-3 py-2 border-b border-border">Method</th>
                            <th className="px-3 py-2 border-b border-border">Path</th>
                            <th className="px-3 py-2 border-b border-border">Summary</th>
                            <th className="px-3 py-2 border-b border-border">Payload Models</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-border">
                          {productionCodebase.manifest.apiContract.map((ep, i) => (
                            <tr key={i} className="hover:bg-sunken/50">
                              <td className="px-3 py-2 font-mono font-bold">
                                <span
                                  className={`rounded px-1.5 py-0.5 text-[10px] ${
                                    ep.method === "GET"
                                      ? "bg-blue-500/20 text-blue-400"
                                      : ep.method === "POST"
                                      ? "bg-emerald-500/20 text-emerald-400"
                                      : ep.method === "DELETE"
                                      ? "bg-red-500/20 text-red-400"
                                      : "bg-amber-500/20 text-amber-400"
                                  }`}
                                >
                                  {ep.method}
                                </span>
                              </td>
                              <td className="px-3 py-2 font-mono text-foreground font-bold">
                                {ep.path}
                              </td>
                              <td className="px-3 py-2 text-muted-foreground">{ep.summary}</td>
                              <td className="px-3 py-2 font-mono text-[11px] text-muted-foreground max-w-xs truncate">
                                {ep.requestBody ? `Req: ${ep.requestBody}` : "Req: None"}
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </div>

                  {/* Database Schema DDL Contract */}
                  <div className="panel border-2 border-border p-5 space-y-3">
                    <div className="flex items-center justify-between gap-3">
                      <h4 className="font-display text-lg font-bold flex items-center gap-2">
                        <span>🗄️</span>
                        <span>Database DDL Schema (PostgreSQL)</span>
                      </h4>
                      <button
                        onClick={() => handleCopyProdCode(productionCodebase.manifest.databaseContract)}
                        className="btn-brutal text-xs px-3 py-1 font-bold bg-background"
                      >
                        📋 Copy DDL
                      </button>
                    </div>
                    <div className="bg-zinc-950 p-4 rounded-lg font-mono text-xs text-zinc-100 overflow-x-auto max-h-[350px]">
                      <pre className="whitespace-pre">
                        <code>{productionCodebase.manifest.databaseContract}</code>
                      </pre>
                    </div>
                  </div>

                  {/* Environment Variables Contract */}
                  <div className="panel border-2 border-border p-5 space-y-3">
                    <h4 className="font-display text-lg font-bold flex items-center gap-2">
                      <span>⚙️</span>
                      <span>Environment Variables Template (.env.example)</span>
                    </h4>
                    <div className="bg-zinc-950 p-4 rounded-lg font-mono text-xs text-emerald-400 overflow-x-auto">
                      <pre className="whitespace-pre">
                        <code>{productionCodebase.manifest.envContract.join("\n")}</code>
                      </pre>
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
