import json
import time
import subprocess
import requests
from openai import OpenAI
from app.core.config import settings

# Initialize OpenAI client to connect to Nvidia API as fallback
client = OpenAI(
    api_key=settings.NVIDIA_API_KEY,
    base_url=settings.NVIDIA_BASE_URL
)

_gcloud_token = None
_token_expiry = 0

def get_vertex_token():
    global _gcloud_token, _token_expiry
    now = time.time()
    if not _gcloud_token or now > _token_expiry:
        # Standard GCP Cloud Run runtime auth
        try:
            import google.auth
            import google.auth.transport.requests
            creds, _ = google.auth.default(scopes=["https://www.googleapis.com/auth/cloud-platform"])
            auth_req = google.auth.transport.requests.Request()
            creds.refresh(auth_req)
            if creds.token:
                _gcloud_token = creds.token
                _token_expiry = now + 3000
                return _gcloud_token
        except Exception:
            pass

        # Local development gcloud CLI fallback
        try:
            res = subprocess.run(
                "gcloud auth print-access-token",
                shell=True,
                capture_output=True,
                text=True,
                timeout=15
            )
            token = res.stdout.strip()
            if token and not token.startswith("ERROR"):
                _gcloud_token = token
                _token_expiry = now + 3000
                return _gcloud_token
        except Exception as e:
            print(f"Error fetching gcloud token: {e}")
    return _gcloud_token

def call_vertex_gemini(prompt: str, system_instruction: str = None, temperature: float = 0.4, max_tokens: int = 8192):
    token = get_vertex_token()
    if not token:
        raise RuntimeError("No Google Cloud access token available. Make sure gcloud is authenticated.")
        
    model_name = settings.GCP_MODEL
    url = f"https://{settings.GCP_LOCATION}-aiplatform.googleapis.com/v1/projects/{settings.GCP_PROJECT_ID}/locations/{settings.GCP_LOCATION}/publishers/google/models/{model_name}:generateContent"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json"
    }
    payload = {
        "contents": [
            {
                "role": "user",
                "parts": [{"text": prompt}]
            }
        ],
        "generationConfig": {
            "temperature": temperature,
            "maxOutputTokens": max_tokens
        }
    }
    if system_instruction:
        payload["systemInstruction"] = {
            "parts": [{"text": system_instruction}]
        }
    res = requests.post(url, headers=headers, json=payload, timeout=60)
    if res.status_code == 404 and model_name != "gemini-2.5-pro":
        # Fallback to gemini-2.5-pro if specific version alias returned 404
        fallback_url = f"https://{settings.GCP_LOCATION}-aiplatform.googleapis.com/v1/projects/{settings.GCP_PROJECT_ID}/locations/{settings.GCP_LOCATION}/publishers/google/models/gemini-2.5-pro:generateContent"
        res = requests.post(fallback_url, headers=headers, json=payload, timeout=60)
    
    if res.status_code != 200:
        raise RuntimeError(f"Vertex AI error ({res.status_code}): {res.text}")
        
    data = res.json()
    candidates = data.get("candidates", [])
    if not candidates:
        raise RuntimeError("No candidate generated by Vertex AI")
    parts = candidates[0].get("content", {}).get("parts", [])
    return "".join(p.get("text", "") for p in parts)

def call_nvidia(prompt: str, system_instruction: str = None, temperature: float = 0.4, max_tokens: int = 4096):
    messages = []
    if system_instruction:
        messages.append({"role": "system", "content": system_instruction})
    messages.append({"role": "user", "content": prompt})
    response = client.chat.completions.create(
        model=settings.NVIDIA_MODEL,
        messages=messages,
        temperature=temperature,
        max_tokens=max_tokens
    )
    return response.choices[0].message.content

def call_llm(prompt: str, system_instruction: str = None, temperature: float = 0.4, max_tokens: int = 4096):
    """
    LLM Router:
    - In PRODUCTION: Uses Google Cloud Vertex AI (Gemini 3.1 Pro).
    - In DEVELOPMENT: Uses Nvidia NIM model (Nemotron).
    """
    is_production = settings.ENVIRONMENT.lower() == "production"

    if is_production:
        # Production: Primary is Vertex AI Gemini 3.1 Pro
        try:
            return call_vertex_gemini(prompt, system_instruction, temperature, max_tokens)
        except Exception as e:
            print(f"Vertex AI error in production: {e}. Falling back to Nvidia...")
            return call_nvidia(prompt, system_instruction, temperature, max_tokens)
    else:
        # Development: Primary is Nvidia NIM model
        try:
            return call_nvidia(prompt, system_instruction, temperature, max_tokens)
        except Exception as e:
            print(f"Nvidia NIM error in development: {e}. Falling back to Vertex AI...")
            return call_vertex_gemini(prompt, system_instruction, temperature, max_tokens)

def _extract_json(content: str):
    content = content.strip()
    if content.startswith("```json"):
        content = content[7:]
    elif content.startswith("```"):
        content = content[3:]
    if content.endswith("```"):
        content = content[:-3]
    content = content.strip()
    try:
        return json.loads(content)
    except json.JSONDecodeError:
        first_brace = content.find('{')
        first_bracket = content.find('[')
        start = -1
        if first_brace != -1 and first_bracket != -1:
            start = min(first_brace, first_bracket)
        elif first_brace != -1:
            start = first_brace
        elif first_bracket != -1:
            start = first_bracket

        last_brace = content.rfind('}')
        last_bracket = content.rfind(']')
        end = max(last_brace, last_bracket)

        if start != -1 and end != -1 and end > start:
            return json.loads(content[start:end+1])
        raise

def generate_raw_json(system: str, prompt: str):
    """
    Gateway function for generating typed JSON from system and user prompts.
    """
    content = call_llm(prompt=prompt, system_instruction=system, temperature=0.4, max_tokens=8192)
    return _extract_json(content)

def generate_project_ideas(student_profile: dict, model_name: str = None):
    """
    Step 3: Generate personalized project ideas based on the student profile.
    """
    prompt = f"""
    You are an AI career and project advisor for final-year students.
    Based on the following student profile, generate 3 personalized practical project ideas.
    
    Student Profile:
    {json.dumps(student_profile, indent=2)}
    
    Return the response strictly as a JSON array of objects with the following keys:
    name, problem, solution, target_users, difficulty_level, estimated_development_time, required_skills (list of strings).
    Do not include markdown blocks or any other text, just the raw JSON array.
    """
    content = call_llm(prompt, temperature=0.7, max_tokens=2048)
    return _extract_json(content)

def refine_project_ideas(student_profile: dict, current_ideas: list, feedback: str, model_name: str = None):
    """
    Step 5: Refine project ideas based on student feedback.
    """
    prompt = f"""
    You are an AI career and project advisor.
    The student previously received these project ideas:
    {json.dumps(current_ideas, indent=2)}
    
    The student's profile is:
    {json.dumps(student_profile, indent=2)}
    
    The student provided the following feedback/request for changes:
    "{feedback}"
    
    Based on this feedback, generate 3 new or refined practical project ideas that better suit their request while still aligning with their profile.
    
    Return the response strictly as a JSON array of objects with the following keys:
    name, problem, solution, target_users, difficulty_level, estimated_development_time, required_skills (list of strings).
    Do not include markdown blocks or any other text, just the raw JSON array.
    """
    content = call_llm(prompt, temperature=0.7, max_tokens=2048)
    return _extract_json(content)

def analyze_project_feasibility(student_profile: dict, project_idea: dict, model_name: str = None):
    """
    Step 6: Analyze the feasibility of a specific project for the student.
    """
    prompt = f"""
    You are an AI career and technical advisor.
    Evaluate the feasibility of the following project idea for this specific student.
    
    Student Profile:
    {json.dumps(student_profile, indent=2)}
    
    Project Idea:
    {json.dumps(project_idea, indent=2)}
    
    Analyze whether this project is realistically achievable for the student given their skills and available time.
    Provide a skill match score (0-100) and an interest match score (0-100).
    Provide a detailed explanation. If it's too difficult, suggest a brief learning roadmap or simplifications.
    
    Return the response strictly as a JSON object with the following keys:
    skill_match_score (integer), interest_match_score (integer), feasibility_explanation (string).
    Do not include markdown blocks or any other text, just the raw JSON object.
    """
    content = call_llm(prompt, temperature=0.4, max_tokens=1024)
    return _extract_json(content)

def generate_project_blueprint(student_profile: dict, project_idea: dict, model_name: str = None):
    """
    Step 8 & 9: Complete Project Blueprint Generation (AI Project Architect).
    """
    prompt = f"""
    You are an expert AI Software Architect and Senior Technical Lead.
    Create an in-depth, production-ready, practical Project Blueprint for the selected final-year student project.
    
    Student Profile:
    {json.dumps(student_profile, indent=2)}
    
    Selected Project Idea:
    {json.dumps(project_idea, indent=2)}
    
    Generate a complete project blueprint adhering STRICTLY to the following JSON structure:
    {{
      "overview": {{
        "project_name": "{project_idea.get('name', 'Project')}",
        "problem_statement": "Detailed problem statement",
        "proposed_solution": "Detailed solution description",
        "project_objectives": ["objective 1", "objective 2", "objective 3"],
        "target_users": "Target audience description",
        "expected_impact": "Expected academic and real-world impact"
      }},
      "features": {{
        "core_mvp": ["MVP feature 1", "MVP feature 2", "MVP feature 3"],
        "advanced_features": ["Advanced feature 1", "Advanced feature 2"],
        "future_improvements": ["Improvement 1", "Improvement 2"]
      }},
      "tech_stack": [
        {{
          "name": "Technology Name",
          "category": "Frontend | Backend | Database | AI/ML | DevOps/Hosting | Tools",
          "why_selected": "Why chosen based on student skills and project needs",
          "how_used": "Exact role in this project"
        }}
      ],
      "system_architecture": {{
        "overview": "Detailed description of system architecture style and communication protocols",
        "components": [
          {{"component": "Frontend Client", "description": "Role and tech"}},
          {{"component": "Backend API Server", "description": "Endpoints and business logic"}},
          {{"component": "Database Layer", "description": "Data storage and modeling"}}
        ],
        "data_flow": ["Step 1: User action...", "Step 2: API processing...", "Step 3: Database query...", "Step 4: Response render..."]
      }},
      "development_roadmap": [
        {{
          "phase_number": 1,
          "phase_name": "Project Planning & Requirement Definition",
          "objectives": "Finalize scope and technical specifications",
          "tasks": ["Task 1", "Task 2"],
          "deliverables": "SRS document and wireframes"
        }},
        {{
          "phase_number": 2,
          "phase_name": "Project Setup & Environment Configuration",
          "objectives": "Initialize repositories, dependencies, and environments",
          "tasks": ["Task 1", "Task 2"],
          "deliverables": "Configured repository and working dev server"
        }},
        {{
          "phase_number": 3,
          "phase_name": "Database Design & Integration",
          "objectives": "Design schema, setup database connection, and create tables",
          "tasks": ["Task 1", "Task 2"],
          "deliverables": "ER diagram and migration scripts"
        }},
        {{
          "phase_number": 4,
          "phase_name": "Backend Development",
          "objectives": "Implement RESTful API endpoints and business logic",
          "tasks": ["Task 1", "Task 2"],
          "deliverables": "Tested backend endpoints"
        }},
        {{
          "phase_number": 5,
          "phase_name": "Frontend Development",
          "objectives": "Build UI components and integrate with backend APIs",
          "tasks": ["Task 1", "Task 2"],
          "deliverables": "Responsive user interface"
        }},
        {{
          "phase_number": 6,
          "phase_name": "AI Integration (if applicable)",
          "objectives": "Integrate AI models, API keys, and prompt pipelines",
          "tasks": ["Task 1", "Task 2"],
          "deliverables": "Working AI feature pipeline"
        }},
        {{
          "phase_number": 7,
          "phase_name": "Testing & Quality Assurance",
          "objectives": "Execute unit, integration, and user-flow tests",
          "tasks": ["Task 1", "Task 2"],
          "deliverables": "Test reports and bug fixes"
        }},
        {{
          "phase_number": 8,
          "phase_name": "Deployment & Presentation Prep",
          "objectives": "Deploy to cloud hosting, document setup, and prepare demo",
          "tasks": ["Task 1", "Task 2"],
          "deliverables": "Live production URL and project report"
        }}
      ],
      "challenges_and_solutions": [
        {{
          "challenge": "Key technical bottleneck or risk",
          "solution": "Recommended mitigation and implementation strategy"
        }}
      ]
    }}

    Rules:
    1. Tailor the tech stack and roadmap to the student's existing skills, filling gaps realistically.
    2. Return ONLY the valid JSON object. No Markdown code fences, no extra text.
    """
    content = call_llm(prompt, temperature=0.4, max_tokens=4096)
    return _extract_json(content)

def mentor_chat_and_refine(
    student_profile: dict,
    project_idea: dict,
    current_blueprint: dict,
    chat_history: list,
    student_message: str,
    model_name: str = None
):
    """
    Steps 10 & 11: Interactive AI Project Mentor and Continuous Blueprint Refinement.
    """
    prompt = f"""
    You are an expert AI Technical Project Mentor and Senior Software Architect.
    You are having an interactive mentoring session with a final-year student regarding their project blueprint.
    
    Student Profile:
    {json.dumps(student_profile, indent=2)}
    
    Selected Project Idea:
    {json.dumps(project_idea, indent=2)}
    
    Current Project Blueprint:
    {json.dumps(current_blueprint, indent=2)}
    
    Recent Chat History:
    {json.dumps(chat_history[-6:], indent=2) if chat_history else "No previous conversation."}
    
    Student's Latest Message:
    "{student_message}"
    
    Your Tasks:
    1. Act as an encouraging, clear, and highly knowledgeable technical mentor.
    2. Address the student's question, concern, or modification request directly.
    3. Determine if the student's request requires a modification to the Project Blueprint.
    4. If a modification IS required:
       - Set "blueprint_updated": true.
       - In "updated_blueprint", provide the complete, updated project blueprint.
    5. If NO modification is needed:
       - Set "blueprint_updated": false.
       - Set "updated_blueprint": null.

    Respond STRICTLY with a valid JSON object matching this schema:
    {{
      "mentor_response": "Your thorough, helpful, conversational answer to the student.",
      "blueprint_updated": true,
      "updated_blueprint": {{ ... }}
    }}
    (Note: If blueprint_updated is false, updated_blueprint should be null).

    Rules:
    - Respond ONLY with the raw JSON object. No Markdown fences, no extra text.
    """
    content = call_llm(prompt, temperature=0.5, max_tokens=4096)
    return _extract_json(content)
